name: novashop
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^3.3.0
  cloud_firestore: ^3.1.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.0
  cubit: ^7.0.0
  provider: ^6.0.0
  http: ^0.13.4
  shared_preferences: ^2.0.8

flutter:
  uses-material-design: true
